import navBar from './Navbar';
import logIn from './LogIn';
import onboardingForm from './OnboardingForm';
import header from './Header';
import signUp from './SignUp';
import newProfile from './NewProfile';
import accountSettingsForm from './AccountSettingsForm';
import warningModal from './WarningModal';
import createNewProfileButton from './CreateNewProfileButton';
import largeCard from './LargeCard';
import candidateCard from './CandidateCard';
import searchBar from './SearchBar';
import dropDown from './DropDown';
import table from './Table';
import editProfileForm from './EditProfileForm';

export const NavBar = navBar;
export const LogIn = logIn;
export const OnboardingForm = onboardingForm;
export const Header = header;
export const SignUp = signUp;
export const NewProfile = newProfile;
export const AccountSettingsForm = accountSettingsForm;
export const CreateNewProfileButton = createNewProfileButton;
export const LargeCard = largeCard;
export const WarningModal = warningModal;
export const CandidateCard = candidateCard;
export const Dropdown = dropDown;
export const SearchBar = searchBar;
export const EditProfileForm = editProfileForm;
export const Table = table;
